<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Links -->
  <!-- Camera base -->
  <link name="gripper_base_link">
    <visual>
      <geometry>
        <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_heigth}"/>
      </geometry>
    </visual>
  </link>
  <!-- Camera finger -->
  

<!-- Joints -->
  <!-- Gripper base to arm -->
  <joint name="gripper_base_to_arm_joint" type="fixed">
    <parent link="arm_short_link"/>
    <child link="gripper_base_link"/>
    <origin xyz="${arm_short_length+(gripper_base_length/2)} ${0.01} ${(gripper_base_heigth/2)-(arm_short_heigth/2)}" rpy="0 0 0"/>
  </joint>

  
  <link name="left_finger_link">
    <visual>
      <geometry>
        <box size="${gripper_finger_length} ${gripper_finger_width} ${gripper_finger_heigth}"/>
      </geometry>
    </visual>
  </link>
  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="left_finger_link"/>
    <origin xyz="${gripper_finger_length/2} ${(gripper_finger_range+(gripper_finger_width/2))-0.01} ${-gripper_finger_heigth}" rpy="0 0 0"/>
    <limit lower="0" upper="${gripper_finger_range}" effort="10.0" velocity="1.0"/>
    <axis xyz="0 -1 0"/>
  </joint>

  <link name="right_finger_link">
    <visual>
      <geometry>
        <box size="${gripper_finger_length} ${gripper_finger_width} ${gripper_finger_heigth}"/>
      </geometry>
    </visual>
  </link>
  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base_link"/>
    <child link="right_finger_link"/>
    <origin xyz="${gripper_finger_length/2} ${-(gripper_finger_range+(gripper_finger_width/2))-0.01} ${-gripper_finger_heigth}" rpy="0 0 0"/>
    <limit lower="0" upper="${gripper_finger_range}" effort="10.0" velocity="1.0"/>
    <axis xyz="0 1 0"/>
    <mimic joint="left_finger_joint" multiplier="1.0" offset="0.0"/>
  </joint>

</robot>